version: '3.1'

services:

  simples:
    image: simples
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - 5005:5000

  produto:
    image: produto
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - 5010:5000